 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  dvc: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      num_bins: 75
      output_format: <>
      annotations:
        train:
          url: /nfs/data/data/youcook2/annotations/train_dvc_titles.json
          storage: /nfs/data/data/youcook2/annotations/train_dvc_titles.json
      videos:
        storage: /nfs/data/data
